name: Python application

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/app_python.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
  
      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with: 
          path: |
            ~/.cache/pip
            venv
          key: ${{ runner.os }}-pip-${{ hashFiles('app_python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.x"
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app_python/requirements.txt
  
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@0.4.0
        continue-on-error: true
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=app_python/requirements.txt --skip-unresolved
        
      - name: Linter - flake8, Autocorrector - black
        run: |
          cd app_python
          pre-commit run --all-files
      
      - name: Test with pytest
        run: |
          cd app_python
          python3 -m pytest

  docker: 
    runs-on: ubuntu-latest
    needs: build-test
    
    steps:
      - uses: actions/checkout@v4.1.0
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build and push
        uses: docker/build-push-action@v5.0.0
        with:
          context: app_python
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/app_python:latest
            ${{ secrets.DOCKER_USERNAME }}/app_python:${{ github.sha }}
